NOTIFICATION_SERVICE_BASE_PATH: "http://notification-service.preprod3:8080"
OPERATION_SERVICE_BASE_PATH: "http://operations-service.preprod3:8080"
JOB_SERVICE_BASE_PATH: "http://job-service.preprod3:8080"
POCKET_SERVICE_BASE_PATH: "http://pocket-service.preprod3:8080"
BROADCAST_SERVICE_BASE_PATH: "http://broadcast-service.preprod3:8080"
INCENTIVES_SERVICE_BASE_PATH: "http://incentives-service.preprod3:8080"
NEWS_PROMOTION_SERVICE: "http://news-promotions-service.preprod3:8080"
AMAZON_S3_BUCKET_NAME : "rider-static-content-preprod3"
AMAZON_S3_EXTERNAL_BUCKET_NAME : "rider-external-content-preprod3"
COGNITO_URL_APP: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_o70Wdkbyc
COGNITO_URL_OPS: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_bn9ChdPT1
SMS_SERVICE_STATUS: DISABLED
KAFKA_REPLICA: "3"
PDPA_BASE_PATH: "https://b2b-apis-qa.alp-robinhood.com"
REDIS_PRIMARY_HOST: rider-qa-elasticache-redis.l9akz6.ng.0001.apse1.cache.amazonaws.com
REDIS_READ_HOST: rider-qa-elasticache-redis-ro.l9akz6.ng.0001.apse1.cache.amazonaws.com
USER_POOL_ID: ap-southeast-1_o70Wdkbyc
KAFKA_PARTITION_JOBSTATUS: "150"
KAFKA_PARTITION_NOTIFICATION: "25"
KAFKA_PARTITION_RIDERAVAIL: "25"
KAFKA_PARTITION_STATUSUPDATE: "100"
