---
# Source: environment/templates/devops-config/deployment/deployment-vars-{{env}}.yml
# This file was generated at  using generator Version: 

DEPLOYMENT:
    ENV: prod
    NAMESPACE: prod
    CONFIG_FILES:
        - "src/main/resources/config/rider-service.default.yaml"
        - "src/main/resources/config/rider-service.prod.yaml"

APP:
    REPLICA: 125
    HPA:
      ENABLED: 0
      MIN_REPLICA: 3
      MAX_REPLICA: 6
      CPU_UTILIZATION: 65
      MEMORY_UTILIZATION: 80
    CONTAINER:
      MEMORY:
        REQUEST: 1Gi
        LIMIT: 2Gi
      CPU:
        REQUEST: 1
        LIMIT: 2
    ENVIRONMENT:
      - KEY: logs.Dir
        VALUE: "/apps/logs/prod/rider-service/"
