
import io.gatling.core.Predef._
import io.gatling.http.Predef._

class VehicleRegistrationCreateUpdate extends Simulation {

  val httpProtocol = http
    .baseUrl("http://localhost:8080")
    .inferHtmlResources()
    .acceptHeader("*/*")
    .acceptEncodingHeader("gzip, deflate")
    .contentTypeHeader("application/json")
    .userAgentHeader("PostmanRuntime/7.26.8")

  val headers = Map("Content-Type"->"application/json")


  val scn = scenario("VehicleRegistrationCreateUpdate")
    .exec(http("request_0")
      .post("/profile/1000/vehicle-details")
      .headers(headers)
      .body(RawFileBody("src/test/resources/recordedsimulation/vehicleregistrationcreateupdate/0000_request.json")))
    .pause(17)
    .exec(http("request_1")
      .post("/profile/10001/vehicle-details")
      .headers(headers)
      .body(RawFileBody("src/test/resources/recordedsimulation/vehicleregistrationcreateupdate/0001_request.json")))
    .pause(9)
    .exec(http("request_2")
      .post("/profile/10002/vehicle-details")
      .headers(headers)
      .body(RawFileBody("src/test/resources/recordedsimulation/vehicleregistrationcreateupdate/0002_request.json")))
    .pause(8)
    .exec(http("request_3")
      .post("/profile/10003/vehicle-details")
      .headers(headers)
      .body(RawFileBody("src/test/resources/recordedsimulation/vehicleregistrationcreateupdate/0003_request.json")))
    .pause(13)
    .exec(http("request_4")
      .post("/profile/10004/vehicle-details")
      .headers(headers)
      .body(RawFileBody("src/test/resources/recordedsimulation/vehicleregistrationcreateupdate/0004_request.json")))
    .pause(3)
    .exec(http("request_5")
      .post("/profile/10004/vehicle-details")
      .headers(headers)
      .body(RawFileBody("src/test/resources/recordedsimulation/vehicleregistrationcreateupdate/0005_request.json")))
    .pause(12)
    .exec(http("request_6")
      .post("/profile/10004/vehicle-details")
      .headers(headers)
      .body(RawFileBody("src/test/resources/recordedsimulation/vehicleregistrationcreateupdate/0006_request.json")))
    .pause(13)
    .exec(http("request_7")
      .put("/profile/10004/vehicle-details")
      .headers(headers)
      .body(RawFileBody("src/test/resources/recordedsimulation/vehicleregistrationcreateupdate/0007_request.json")))
    .pause(3)
    .exec(http("request_8")
      .put("/profile/10004/vehicle-details")
      .headers(headers)
      .body(RawFileBody("src/test/resources/recordedsimulation/vehicleregistrationcreateupdate/0008_request.json")))
    .pause(1)
    .exec(http("request_9")
      .put("/profile/10004/vehicle-details")
      .headers(headers)
      .body(RawFileBody("src/test/resources/recordedsimulation/vehicleregistrationcreateupdate/0009_request.json")))
    .pause(3)
    .exec(http("request_10")
      .put("/profile/10004/vehicle-details")
      .headers(headers)
      .body(RawFileBody("src/test/resources/recordedsimulation/vehicleregistrationcreateupdate/0010_request.json"))
      .resources(http("request_11")
        .put("/profile/10004/vehicle-details")
        .headers(headers)
        .body(RawFileBody("src/test/resources/recordedsimulation/vehicleregistrationcreateupdate/0011_request.json"))))

  setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}